# Site settings
title: Naveen Balu
description: 'Portfolio Page'
url: 'https://navn24.github.io/'
baseurl: ''
profilepic: '/images/naveen.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '36060caf6e.js'

author:
  name: 'Naveen Balu'
  email: navnbalu@gmail.com
  # mastodon: ''
  # twitter_username: ''
#  facebook_username: joshgerdes
  github_username:  navn24
  linkedin_username:  naveen-balu
  # meetup_name: ''

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
