# Site settings
title: Naveen Balu
description: 'Business Card Page'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/naveen.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '36060caf6e.js'

author:
  name: 'Naveen Balu'
  email: navnbalu@gmail.com
  mastodon: tzuehlke@mstdn.social
  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  navn24
  linkedin_username:  naveen-balu
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
